### ISSUE TITLE
Project does not compile and link

### ISSUE THREAD

**Issue by idea--list** [maddogjt/fastled_espidf_s3#1]
Hi there,

I am trying to integrate this repo in a project of mine.
If i place #include FastLED.h inside the main.cpp only everything is fine.
However if i try to place the #include into an externs.h header file to allow RGB LED control from several source files found in the /components folder of my project, then building always fails (of course i include externs.h into all components which should have control of the RGB LED).

The error message in the console is:
fatal error: FastLED.h: No such file or directory

If i put #include FastLED.h into any source files of the /components folder (instead of externs.h or main.cpp inside /main folder)
then i get:
FastLED.h error: expected '=', ',', ';', 'asm' or '_attribute_' before '<' token

I have no idea what i might be doing wrong or how to solve the problem. Can anyone help?

**Comment by projects-land** [comment]
The component CMakeLists.txt likely requires a dependency to the FastLEDShim component in order for the correct include paths to be added.

**Comment by idea--list** [comment]
Thanks for the hint, will try to look into that!

**EDIT:** Turns out i was not paying attention and tried to #include FastLED.h into a plain C file...
